db:
    container_name: live_scores_db
    image: postgres
    restart: always
web:
    container_name: live_scores
    build: .
    restart: always
    command: /usr/bin/supervisord -c /code/deployment/supervisord.conf
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    links:
        - db
    tty: true
