# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='url',
            new_name='url_id',
        ),
    ]
