# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20151220_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('local', models.BooleanField(default=True)),
                ('local_score', models.IntegerField()),
                ('visitant_score', models.IntegerField()),
                ('url_id', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Team')),
            ],
        ),
    ]
