# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='num_matches',
            field=models.IntegerField(default=0),
        ),
    ]
